<?php


    use Game\Game;
    use PHPUnit\Framework\TestCase;

    class GameTest extends TestCase
    {
        protected $game;

        public function setUp(): void
        {
           $this->game = new Game(); /// TODO: Change the autogenerated stub
        }

        public function test_createRockQuestion_shouldDefinedText() {

            $this->assert($this->game->createRockQuestion(1),'Rock Question  1');
        }
    }
